#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Jinghan Alina Hu 2022 DREU

# Short bio or description (displayed in the header)
description: Vera C. Rubin Observatory's Legacy Survey of Space and Time (LSST) is a ten-year astronomical imaging survey that will begin in 2024 from a new telescope in Chile. Instead of soliciting individual requests for what the telescope should point at, the LSST will uniformly survey the sky every three nights in six color filters to essentially create a decade-long “high resolution color movie” of the entire southern sky, and share massive quantities of data products with the astronomy community. To accomplish this, there is a complex scheduler algorithm that takes into account various science priorities, what has recently been observed, how long it takes the telescope to move to a new target, etc. A new challenge has recently come up with a hugely increasing number of bright low-Earth-orbit satellites (e.g., Starlink) that will leave streaks in LSST images. However, there is not yet a plan to incorporate known commercial satellites into the Rubin scheduler so the worst of them may be avoided. In this project, we seek to create realistic simulated forecasts of satellite trajectories and brightnesses, build a tool that uses that data to create new scheduler constraints, and test what the impact is to various Rubin LSST observing programs.  

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: ahu@hmc.edu
  facebook:
  flickr:
  rss: # just type anything here for a working RSS icon

# Your website URL (e.g. http://ajstent.github.io)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman
